### ISSUE TITLE
Use geographic coordinates from gazebo::World for the GPS and Magnetometer plugin

### ISSUE THREAD

**Issue by meyerj** [tu-darmstadt-ros-pkg/hector_gazebo#15]
Gazebo 2.0 introduced the `gazebo::common::SphericalCoordinates` class and a `gazebo::World::getSphericalCoordinates()` member function:
https://bitbucket.org/osrf/gazebo/src/11bc8a872c00526c8dcea4cf4c7600c74979b404/gazebo/common/SphericalCoordinates.hh?at=default

Spherical (geographic) coordinates can be specified in the SDF world file:
http://sdformat.org/spec?ver=1.5&elem=world#world_spherical_coordinates

The `gazebo_ros_gps` and `gazebo_ros_magnetic` plugins should use the coordinates and/or heading offset provided there as a fallback if plugin parameters are not set.

**Comment by MasterHansCoding** [comment]
first link dead :'(

**Comment by Martin-Oehler** [comment]
Gazebo moved to GitHub:
https://github.com/osrf/gazebo/blob/gazebo11/gazebo/common/SphericalCoordinates.hh

**Comment by StefanFabian** [comment]
Implemented in #83
