### ISSUE TITLE
hector_gazebo failing to build in Kinetic

### ISSUE THREAD

**Issue by tfoote** [tu-darmstadt-ros-pkg/hector_gazebo#34]
This appears to be a missing dependency on pthread. Which was previously masked by gazebo_ros and gazebo_plugins

It was released 4 days ago with the dependencies cleaned up: https://github.com/ros/rosdistro/pull/14563 warning that downstream may have an issue with pthreads. 

http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__hector_gazebo_thermal_camera__ubuntu_xenial_amd64__binary/45/console

**Comment by tfoote** [comment]
There's a known issue in catkin
ros/catkin#856

**Comment by meyerj** [comment]
I don't fully understand what we can do to fix this:
- Wait until https://github.com/ros/catkin/issues/856 has been fixed?
- Do not `find_package(... gazebo_plugins)` in [hector_gazebo_thermal_camera/CMakeLists.txt:7](https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/blob/indigo-devel/hector_gazebo_thermal_camera/CMakeLists.txt#L7)? But we include a header provided by that package.
- Modify the CMake code to find Gazebo or `gazebo_plugins`, without relying on catkin?

What is the recommended solution?

**Comment by tfoote** [comment]
I'm not sure there's discussion at: https://github.com/yujinrobot/kobuki_desktop/issues/50

@j-rivero FYI

**Comment by tfoote** [comment]
Fixed by gazebo_ros_pkgs rollback. Closing.
