### ISSUE TITLE
Unable to get gps reading

### ISSUE THREAD

**Issue by pallyra1** [tu-darmstadt-ros-pkg/hector_gazebo#45]
I am using package hector_gazebo_plugins
I want the gps readings, so for that when I use the command
`rosrun hector_gazebo_plugins gazebo_ros_gps`
I am getting error 
[rosrun] Couldn't find executable named gazebo_ros_gps below /home/pallav/catkin_ws/src/hector_gazebo_plugins

I am new to ROS.
Please help

**Comment by akashpurandare** [comment]
You cannot use the Hector Plugins the way you are using as above. You need to include it inside either the SDF or the URDF file that you are spawning inside the Gazebo environment. To use the model plugins of GPS, use the following example snippet of code:
`<gazebo>
		<plugin filename="libhector_gazebo_ros_gps.so" name="gps_sim">
			<updateRate>10</updateRate>
			<bodyName>gps</bodyName>
			<topicName>/fix</topicName>
			<velocityTopicName>/vel</velocityTopicName>
			<drift>5.0 5.0 5.0</drift>
			<gaussianNoise>0.0000001 0.0000001 0.0000001</gaussianNoise>
			<velocityDrift>0 0 0</velocityDrift>
			<velocityGaussianNoise>0.0000001 0.0000001 0.0000001</velocityGaussianNoise>
		</plugin>
	</gazebo>`
Be mindful of the type of plugin you are using. This particular one is a Model Plugin.
