### ISSUE TITLE
gazebo 9 support?

### ISSUE THREAD

**Issue by mfe7** [tu-darmstadt-ros-pkg/hector_gazebo#48]
In gazebo 9, some of the included libraries (e.g. `gazebo::math::Vector3`) are now part of ignition instead of gazebo. This causes issues when compiling hector_gazebo with gazebo-9, and it seems more involved than just switching the include statements. Are there plans to support the new version of gazebo?

**Comment by tahsinkose** [comment]
I think the support you demanded is already implemented in [PR-44](https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/pull/44). You can refer to it for further details.

**Comment by meyerj** [comment]
> I think the support you demanded is already implemented in PR-44. You can refer to it for further details.

Indeed.
