### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [tu-darmstadt-ros-pkg/hector_gazebo#68]
Would you mind releasing these packages also for the newest distribution ROS Noetic? :)

**Comment by StefanFabian** [comment]
Sure but it will take a few weeks until I can get around to setting up a noetic installation.

**Comment by rgmann** [comment]
Bump. I would also be interested in a Noetic release.

**Comment by StefanFabian** [comment]
Thank you for the bump. I thought it was already released but apparently something isn't working with the build process.
The release repo doesn't have a tag that the build farm is looking for. I'll look into that.

**Comment by rgmann** [comment]
@StefanFabian Thank you!

**Comment by StefanFabian** [comment]
Packages should now be available.

**Comment by NedaRH** [comment]
Could you please provide the link of Noetic release of this package? I couldn't find it.

**Comment by StefanFabian** [comment]
The default branch is always the most up-to-date one for our packages.
There were no changes that weren't compatible with melodic, hence, we did not create a new branch.
As of the noetic release, the ros build farm distributes the packages. You can install them separately or all of them with the meta package `ros-noetic-hector-gazebo`.
