### ISSUE TITLE
Incongruent licensing

### ISSUE THREAD

**Issue by veimox** [tu-darmstadt-ros-pkg/hector_gazebo#69]
Hi! I have noticed that even though the package's license is BSD and that most of the headers in both .h and .cpp files are having the BSD clause, some files are not:

* gazebo_ros_force_based_move.cpp has Apache 2.0 vs the .h that is BSD
* servo_plugin.h has GPLv2 vs the cpp is BSD
* diffdrive_plugin_6w.h has GPLv2 vs the cpp is BSD

I think it would make sense to homogenize all headers to BSD, what do you think?

**Comment by skohlbr** [comment]
Thanks for reporting!
As the force_based_move plugin is based on the Apache 2.0 planar move plugin we'll keep that one, but I fixed the other two via https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/commit/93ec5114dda2d440c175f3be2c7af9543e2d729f which apparently originate from a copy/paste omission (the same headers in gazebo_ros_pkgs are BSD licensed).
