### ISSUE TITLE
Change mag message type to sensor_msgs/MagneticField

### ISSUE THREAD

**Issue by civerachb-cpr** [tu-darmstadt-ros-pkg/hector_gazebo#72]
The mag sensor currently outputs std_msgs/Vector3Stamped messages, which have widely been replaced with sensor_msgs/MagneticField for the purposes of magnetometer sensors.  It would be nice if the plugin could be updated to output messages in the new standard, or at least offer a parameter to switch to the new standard.

**Comment by StefanFabian** [comment]
We will gladly accept a PR with a parameterized change of behavior to ensure backward compatibility!

**Comment by StefanFabian** [comment]
Was added in #73.
