### ISSUE TITLE
update to noetic

### ISSUE THREAD

**Issue by Hc7Hs** [tu-darmstadt-ros-pkg/hector_gazebo#77]
Are there any plugins that adapt to the noetic version?

**Comment by StefanFabian** [comment]
Currently, the only method of using this repository in noetic is to build it from source and I don't know if it is compatible with Noetic and Gazebo 11 or if changes are required.
I will check that in the next weeks but I can not guarantee that a noetic version will be released before the end of the year.

**Comment by CHN-Fancy** [comment]
+1

**Comment by StefanFabian** [comment]
We're in the process of upgrading to noetic right now.
I'll check if it compiles tomorrow and if it does, I'll prepare a release.
