### ISSUE TITLE
IMU Plugin Orientation

### ISSUE THREAD

**Issue by jinbae9875** [tu-darmstadt-ros-pkg/hector_gazebo#79]
Hi. I'm trying to use navsat_transform_node from robot_localization package: http://docs.ros.org/jade/api/robot_localization/html/integrating_gps.html

In order to use this node, I need to make sure that REP-105 convention is followed: https://www.ros.org/reps/rep-0105.html

Basically, the IMU heading's zero point must be pointing east. Is there any way that I can know if hector_gazebo's IMU plugin conforms to this? It's okay if it doesn't, I can adjust the navsat node with yaw_offset, but I do need to know exactly which geographical orientation (N,S,E,W,...) the zero point is directed towards in order to set the offset. Thanks.

**Comment by jinbae9875** [comment]
I figured it out! By default, the robot faces North when yaw is set to 0. You need to set the yaw_offset parameter to pi/2 in order for navsat_transform_node to work properly.

**Comment by StefanFabian** [comment]
Are you sure it is pi/4 and not pi/2?
pi/4 would be equivalent to 45°

**Comment by jinbae9875** [comment]
@StefanFabian StefanFabian Oh shoot you're right I used pi/2. Thanks for pointing it out. Edited.
